name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  # cygwin:
  #   runs-on: windows-latest
  #   steps:
  #     - run: git config --global core.autocrlf input
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.x"
  #     - uses: cygwin/cygwin-install-action@master
  #     - run: python plano test --verbose
  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - run: dnf -y install busybox curl dash ksh mksh nc python /bin/ps sudo tar yash zsh
      - run: cd /usr/bin && ln -s busybox ash
      - run: ./plano test
        env:
          PLANO_COLOR: 1
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: ./plano test
        env:
          PLANO_COLOR: 1
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get -qq update
      - run: apt-get -qq install curl netcat-openbsd python3 sudo
      - run: ./plano test
        env:
          PLANO_COLOR: 1
